#!/bin/bash
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/biconditional.n3 --output ./temp/biconditional-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/cardinality.n3 --output ./temp/cardinality-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/contradiction.n3 --output ./temp/contradiction-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/contradiction2:FAIL.n3 --output ./temp/contradiction2:FAIL-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/counter_example:FAIL.n3 --output ./temp/counter_example:FAIL-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/evennumber:FAIL.n3 --output ./temp/evennumber:FAIL-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/exclusive_disjunction.n3 --output ./temp/exclusive_disjunction-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/ifthisorthatthen.n3 --output ./temp/ifthisorthatthen-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/lisp.n3 --output ./temp/lisp-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/modusTollens.n3 --output ./temp/modusTollens-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/negativeSurface1.n3 --output ./temp/negativeSurface1-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/negativeSurface2.n3 --output ./temp/negativeSurface2-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/nesting.n3 --output ./temp/nesting-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/noGod.n3 --output ./temp/noGod-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/oddnumber.n3 --output ./temp/oddnumber-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/oneGod:FAIL.n3 --output ./temp/oneGod:FAIL-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/R3.n3 https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/R2.n3 https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/R1.n3 https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/Query.n3 https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/Policy2.n3 https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/Policy1.n3 https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/policy/Context.n3 --output ./temp/policy-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/positiveSurface1.n3 --output ./temp/positiveSurface1-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/positiveSurface2.n3 --output ./temp/positiveSurface2-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/range.n3 --output ./temp/range-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/rdfs.n3 --output ./temp/rdfs-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/real_programmer.n3 --output ./temp/real_programmer-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/syntactic_sugar.n3 --output ./temp/syntactic_sugar-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/phochste/Notation3-By-Example/main/log/blogic/trueGod.n3 --output ./temp/trueGod-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/abc.n3 --output ./temp/abc-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/abcd.n3 --output ./temp/abcd-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/bmt.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt1.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt2.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt3.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt4.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt5.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt6.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt7.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt8.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt9.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/bmt/1tt10.n3 --output ./temp/bmt-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/complex.n3 --output ./temp/complex-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/disj-elim.n3 --output ./temp/disj-elim-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/equal.n3 --output ./temp/equal-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/fibonacci.n3 --output ./temp/fibonacci-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/gray-code-counter.n3 --output ./temp/gray-code-counter-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/gps.n3 --output ./temp/gps-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/lubm.n3 --turtle https://raw.githubusercontent.com/josd/eye/master/reasoning/lubm/facts.n3 --output ./temp/lubm-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/peano.n3 --output ./temp/peano-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/rain.n3 --output ./temp/rain-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/sdcoding.n3 --output ./temp/sdcoding-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/slide28a.n3 --output ./temp/slide28a-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/slide28b.n3 --output ./temp/slide28b-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/slide32.n3 --output ./temp/slide32-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/slide33.n3 --output ./temp/slide33-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/socrates.n3 --output ./temp/socrates-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/socrates-star.n3 --output ./temp/socrates-star-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/spo.n3 --output ./temp/spo-answer.n3
eye --quiet --nope --blogic https://raw.githubusercontent.com/josd/eye/master/reasoning/blogic/zebra.n3 --output ./temp/zebra-answer.n3
